# Generated by Django 5.0.7 on 2024-07-17 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=120)),
                ('contact_no', models.CharField(blank=True, max_length=20)),
                ('person_email', models.EmailField(blank=True, max_length=254)),
                ('project_experience', models.TextField(default='add experience', max_length=400)),
                ('ad_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeopleTechSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name_tech', models.CharField(max_length=120)),
                ('contact_no_tech', models.CharField(blank=True, max_length=20)),
                ('person_email_tech', models.EmailField(blank=True, max_length=254)),
                ('project_experience', models.TextField(default='experience', max_length=400)),
                ('ts_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('project_date', models.DateTimeField()),
                ('description', models.TextField(max_length=1000)),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resource_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.peopleadministration')),
                ('resource_tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.peopletechsupport')),
            ],
        ),
    ]
